# Generated by Django 2.2.1 on 2019-06-07 08:43

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=posts.models.user_post_path),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
