# Generated by Django 2.2.1 on 2019-06-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bp',
            field=models.BooleanField(default=False),
        ),
    ]
